Repository gauravsingh1281/Rentalog.in--Frontend, pull requests merged in 2024-10, with the labels that each got.

#169 added hover effect to login and register btn
  src/components/Header-section/Navbar.jsx
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#172 look changed
  src/components/Contact-section/Contact.jsx
  src/components/Contact-section/ContactForm.jsx
  src/components/Contact-section/ContactText.jsx
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#177 [#135]RESOLVE Enhancement of the Footer , Proper Alignment of the Gmap and make this part Responsive
  package-lock.json
  package.json
  src/components/Contact-section/GoogleMap.jsx
  src/components/Footer-section/Footer.jsx
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#189 Adding mouse depth effect animation #170
  src/components/AboutUs-section/AboutUs.jsx
  src/components/Services-section/ServicesCard.jsx
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#152 added missing google icon
  src/pages/Login.jsx
  src/pages/Registration.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#188 updated the contact page layout
  package-lock.json
  src/components/Contact-section/Contact-section.css
  src/components/Contact-section/Contact.jsx
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#194 Added Newsletter feature in footer component
  package-lock.json
  package.json
  src/components/Footer-section/Footer.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#207 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#229 enhanced available cities section
  src/assets/Images/agra-1.jpg
  src/assets/Images/banglore-1.jpg
  src/assets/Images/chennai-1.jpg
  src/assets/Images/chennai-1.png
  src/assets/Images/delhi-1.png
  src/assets/Images/goa-1.jpg
  src/assets/Images/mumbai-1.jpg
  src/assets/Images/none.png
  src/components/Services-section/Services-section.jsx
  src/components/Services-section/ServicesAvailableIn.jsx
  src/components/Services-section/placeName.js
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#235 Submit button centered (issue #205)
  src/components/Contact-section/Contact-section.css
  src/components/Contact-section/ContactForm.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#246 #217 link highlighting
  src/components/Header-section/Navbar.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#261 About us
  index.css
  index.html
  package-lock.json
  package.json
  src/assets/Images/about-1.svg
  src/assets/Images/about-2.jpg
  src/assets/Images/about-3.jpg
  src/assets/Images/about-4.jpg
  src/components/AboutUs-section/AboutCard.jsx
  src/components/AboutUs-section/AboutUs-section.css
  src/components/AboutUs-section/AboutUs.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#221 Create Code of Conduct.md
  Code of Conduct.md
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#254 Enhance the UI of the Services Section
  src/components/Services-section/Services-section.jsx
  src/components/Services-section/ServicesCard.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#259 Fix: Navigate to Home page after successful login
  package-lock.json
  package.json
  src/App.jsx
  src/pages/Login.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#274 added carousel
  package-lock.json
  package.json
  src/assets/Images/agra-1.png
  src/assets/Images/banglore-1.png
  src/assets/Images/carousel2.jpg
  src/assets/Images/carousel2.png
  src/assets/Images/carousel3.jpg
  src/assets/Images/carousel3.png
  src/assets/Images/goa-1.png
  src/assets/Images/mumbai-1.png
  src/assets/Images/red-house.png
  src/components/Header-section/Header-section.css
  src/components/Header-section/Header.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#294 added animation on scroll
  package-lock.json
  package.json
  src/components/AboutUs-section/AboutCard.jsx
  src/components/Contact-section/ContactText.jsx
  src/components/Contact-section/GoogleMap.jsx
  src/components/Services-section/Services-section.jsx
  src/components/Services-section/ServicesAvailableIn.jsx
  src/components/Services-section/ServicesCard.jsx
  src/components/Services-section/services.js
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#248 Update README.md Add Some Screenshots
  README.md
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#264 Add Service Links to Footer and Create Individual Service Pages
  src/components/Footer-section/Footer.jsx
  src/components/dashboard-components/PaymentsRecord/PaymentsRecord.jsx
  src/components/dashboard-components/PropertyListing/PropertyListing.jsx
  src/components/dashboard-components/TotalRentCollected/TotalRentCollected.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#287 Updated the talwind css
  tailwind.config.js
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#298 Added a responsive password strength level meter in signup page
  package-lock.json
  package.json
  src/pages/Registration.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level3

#321 added 4 oauth for regestration also
  src/pages/Registration.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#268 added icons
  src/pages/Login.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#281 [update]: updated footer section of the website to look more user friendly.
  src/components/Footer-section/Footer.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#315 enhanced go-to-top button
  package-lock.json
  package.json
  src/assets/Icons/arrow-up.png
  src/pages/Home.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#305 Implementing React Hook Form
  package-lock.json
  package.json
  src/components/Contact-section/ContactForm.jsx
  src/components/connectUs-section/Form.jsx
  src/pages/Login.jsx
  src/pages/Registration.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#328 added gsap sliding animation with stagger to navbar
  package-lock.json
  src/components/Header-section/Navbar.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level3

#312 Cards
  package-lock.json
  package.json
  src/components/dashboard-components/PropertyListing/PropertyListing.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#308 Added show password button #280
  index.html
  src/pages/Login.jsx
  src/pages/Registration.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#331 added new logo of twitter in whole webpage
  src/components/Contact-section/Contact.jsx
  src/components/Footer-section/Footer.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#339 [Feat] : Adding Multi-Lingual Support to Rentalog
  src/components/Header-section/GoogleTranslate.jsx
  src/components/Header-section/Navbar.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level3

#340 Made the modification and add more decoration
  src/components/AboutUs-section/AboutUs-section.css
  src/components/Contact-section/Contact-section.css
  src/components/Header-section/Header-section.css
  src/components/Services-section/Services-section.css
  src/components/testimonial-section/Testimonial.css
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#344 updateed_trusted_mail_services
  src/pages/Login.jsx
  src/pages/Registration.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#301 added chatbot✨
  index.html
  src/pages/Home.jsx
  src/pages/home.css
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level3

#352 fix image size for small screen and about section text size for small screen
  src/components/AboutUs-section/AboutCard.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#372 Links on login and sign up page not Working(issue #299)
  src/App.jsx
  src/pages/ForgotPassword.jsx
  src/pages/Login.jsx
  src/pages/Registration.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#362 Added Contributor's Page
  package-lock.json
  package.json
  src/App.jsx
  src/components/Contributors-page/Contributors.css
  src/components/Contributors-page/Contributors.jsx
  src/components/Footer-section/Footer.jsx
  src/pages/Home.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level3

#314 fix: redirection to Home page after successful registration.
  src/pages/Registration.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#355 Fixed vertical alignment of navbar items
  src/components/Header-section/Navbar.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#401 Fix Image Layout Issues on About Page
  package-lock.json
  src/components/testimonial-section/Testimonial.jsx
  src/pages/home.css
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#404 Added admin dashboard
  package-lock.json
  src/App.jsx
  src/components/Admin-Dashboard/AdminDashboard.css
  src/components/Admin-Dashboard/AdminDashboard.jsx
  src/pages/Login.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#406 Added PRValidator Workflow
  .github/workflows/PRValidator.yml
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level3

#409 made changes in service section and changed the color of newsletter word
  src/components/Footer-section/Footer.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#413 Added width and line height to paragraph. Modified br tags.
  src/components/Header-section/Header-section.css
  src/components/Header-section/Header.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#436 Update README with Metrics Table, Language Table, and Formatting Changes
  README.md
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#385 Added more items in List pricing section and its UI
  src/components/dashboard-components/PropertyListing/PropertyListing.css
  src/components/dashboard-components/PropertyListing/PropertyListing.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#422 Add custom scrollbar styling for better UI/UX #421
  src/App.css
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#476 Update README.md added Stargazers and Forkers section
  README.md
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#475 Update scroll behavior in PropertyListing and TotalRentCollected component
  src/components/dashboard-components/PropertyListing/PropertyListing.jsx
  src/components/dashboard-components/TotalRentCollected/TotalRentCollected.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#429 Fixed email validation and input clearing issue in Footer component
  src/components/AboutUs-section/AboutCard.jsx
  src/components/Footer-section/Footer.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#431 Map fixed - Now map is showing the exact location
  src/components/Contact-section/GoogleMap.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#439 Done enhancements and added some new sections
  CONTRIBUTING.md
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#470 Update Registration.jsx (Redesigning of image)
  src/pages/Registration.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#485 Added Issue Labeler GitHub Action
  .github/workflows/issue_labeler.yaml
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#491 Enhance Navbar Aesthetics with Hover Effects and Improved Button Styles
  src/components/Header-section/Navbar.css
  src/components/Header-section/Navbar.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#492 Update Contact Us Section with SVG Icons
  src/components/Contact-section/Contact.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#495 Modify Navbar & Fix Active state
  src/components/Header-section/Header-section.css
  tailwind.config.js
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#497 Modern scrollbar and progressbar implemented
  src/App.css
  src/components/Header-section/Navbar.jsx
  src/components/Header-section/ProgressBar.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#498 Added blur background Images
  src/assets/Images/BlurAgra.jpg
  src/assets/Images/BlurBangalore.jpg
  src/assets/Images/BlurChennai.jpg
  src/assets/Images/BlurDelhi.jpg
  src/assets/Images/BlurGoa.jpg
  src/assets/Images/BlurMumbai.jpg
  src/components/Services-section/Services-section.jsx
  src/components/Services-section/ServicesAvailableIn.jsx
  src/components/Services-section/placeName.js
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#501 improved the Ui of admin
  src/components/Admin-Dashboard/AdminDashboard.css
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#503 Modified the UI of the select language bar
  src/components/Header-section/GoogleTranslate.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#517 added-coming-soon-page-for-broken-links
  src/App.jsx
  src/components/Footer-section/Footer.jsx
  src/pages/ComingSoon.jsx
  src/pages/index.js
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#480 background-images & 3-d hover effects added to the 'Our Services' cards
  src/assets/Images/services-1.png
  src/assets/Images/services-2.png
  src/assets/Images/services-3.png
  src/assets/Images/services-4.jpg
  src/components/Services-section/Services-section.jsx
  src/components/Services-section/ServicesCard.jsx
  src/components/Services-section/services.js
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#488 New page for Privacy & Policy and Terms & Conditions added
  package-lock.json
  package.json
  src/App.jsx
  src/components/Footer-section/Footer.jsx
  src/components/Privacy-Policy/PrivacyPolicy.css
  src/components/Privacy-Policy/PrivacyPolicy.jsx
  src/components/Terms-Conditions/TermsConditions.css
  src/components/Terms-Conditions/TermsConditions.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#518 Implemented Dark Theme Support
  package-lock.json
  src/App.css
  src/components/Header-section/Navbar.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2

#536 solved #464 added cursor animation finally
  src/App.css
  src/App.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level3

#441 updated github logo and added all social media icons 3d hover effect
  package-lock.json
  src/components/Contact-section/Contact.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#453 chat open added in contact us section
  src/components/Contact-section/ContactText.jsx
  tailwind.config.js
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#523 ADDED HACKTOBERFEST AND GSSOC BANNER ON THE README
  README.md
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#527 Text over lap and button enhancement with hover effect fixed
  package-lock.json
  src/components/Header-section/Header-section.css
  src/pages/Registration.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#538 Eliminate duplicate footer
  package-lock.json
  src/pages/Home.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#568 Fix dark mode text and Twitter logo colors
  package-lock.json
  src/components/Contact-section/Contact.jsx
  src/components/Services-section/Services-section.jsx
Labels: Assigned, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2
