Repository gauravsingh1281/Rentalog.in--Frontend, pull requests merged in 2025-02, with the labels that each got.

#673 Fixed colors on Register page
  src/pages/Registration.jsx
Labels: Assigned, Beginner, SWOC

#681 Fixed the Contributor's Page
  src/components/Contributors-page/Contributors.jsx
Labels: Assigned, Beginner, SWOC

#679 add click sound
  src/assets/mixkit-mouse-click-close-1113.wav
  src/components/Admin-Dashboard/AdminDashboard.jsx
  src/components/Contact-section/Contact.jsx
  src/components/Contact-section/ContactForm.jsx
  src/components/Header-section/Header.jsx
  src/components/Header-section/Navbar.jsx
  src/components/connectUs-section/Connect.jsx
  src/components/connectUs-section/Form.jsx
Labels: Assigned, Beginner, SWOC

#682 Redesigned Privacy Policy Page
  package-lock.json
  package.json
  src/components/Header-section/RentNavbar.jsx
  src/components/Privacy-Policy/PrivacyPolicy.css
  src/components/Privacy-Policy/PrivacyPolicy.jsx
Labels: Assigned, Intermediate, SWOC

#693 Add Rent Calculation Summary Card with Reset Functionality
  package-lock.json
  package.json
  src/components/rent/RentCalculator.css
  src/components/rent/RentCalculator.jsx
Labels: Assigned, SWOC

#703 UI improve of footer part
  src/components/Footer-section/Footer.jsx
Labels: Assigned, Beginner, SWOC

#704 Payment Records & Back Navigation
  package-lock.json
  package.json
  src/App.jsx
  src/components/Admin-Dashboard/AdminDashboard.jsx
  src/components/Contact-section/GoogleMap.jsx
  src/components/Header-section/GoogleTranslate.jsx
  src/components/Header-section/Navbar.jsx
  src/components/Services-section/ServicesCard.jsx
  src/components/Services-section/services.jsx
  src/components/dashboard-components/PaymentsRecord/PaymentsRecord.jsx
  src/components/rent/RentCalculator.css
  src/components/rent/RentCalculator.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
Labels: Assigned, Intermediate, SWOC

#706 Redesigned Terms and Conditions Page
  src/components/Terms-Conditions/TermsConditions.css
  src/components/Terms-Conditions/TermsConditions.jsx
Labels: Assigned, Beginner, SWOC
